run:
  deadline: 5m

linters:
  fast: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
#    - errcheck
    - exhaustive
    - exportloopref
#    - gochecknoglobals
#    - goconst
#    - gocritic
    - godot
    - gofmt
#    - gofumpt
    - goheader
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
#    - gosec
#    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nolintlint
#    - prealloc
    - rowserrcheck
#    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - stylecheck
      text: "ST1005:"

    - linters:
        - errcheck
      text: "Error return value of `d.Set` is not checked"