- project:
    name: h00130372/terraform-provider-openstack
    check:
      jobs:
        - test-create-k8s-cluster
    recheck-trove:
      jobs:
        - terraform-provider-openstack-acceptance-test-trove
    recheck-designate:
      jobs:
        - terraform-provider-openstack-acceptance-test-designate
    recheck-lbaas:
      jobs:
        - terraform-provider-openstack-acceptance-test-lbaas
    recheck-fwaas:
      jobs:
        - terraform-provider-openstack-acceptance-test-fwaas
