# Functional testing for blockstorage_v3
name: functional-blockstorage_v3
on:
  pull_request:
    paths:
      - '.github/workflows/functional-blockstorage_v3.yml'
      - '**blockstorage**'
      - 'CHANGELOG.md'
  schedule:
    - cron: '0 0 * * *'
jobs:
  functional-basic:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["20.04"]
        include:
          - name: "yoga"
            openstack_version: "stable/yoga"
            ubuntu_version: "20.04"
          - name: "xena"
            openstack_version: "stable/xena"
            ubuntu_version: "20.04"
          - name: "wallaby"
            openstack_version: "stable/wallaby"
            ubuntu_version: "20.04"
          - name: "victoria"
            openstack_version: "stable/victoria"
            ubuntu_version: "20.04"
          - name: "ussuri"
            openstack_version: "stable/ussuri"
            ubuntu_version: "18.04"
          - name: "train"
            openstack_version: "stable/train"
            ubuntu_version: "18.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: blockstorage_v3 on OpenStack ${{ matrix.name }} with defaults and run basic acceptance tests
    steps:
      - name: Checkout TPO
        uses: actions/checkout@v3
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.7
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: 's-account,s-container,s-object,s-proxy'
      - name: Checkout go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Run TPO acceptance tests
        run: ./scripts/acceptancetest.sh
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: 'blockstorage.*v3|v3.*blockstorage'
      - name: Generate logs on failure
        run: ./scripts/collectlogs.sh
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: functional-basic-${{ matrix.name }}
          path: /tmp/devstack-logs/*