name: Unit Testing
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - "1.20"

    env:
      GO111MODULE: "on"

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v3

      - name: Run go vet
        run: |
          go vet ./...
      - name: Run unit tests
        run: |
          ./scripts/unittest.sh
